[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/kru-asset-library/api/*"
  status = 200
  to = "/.netlify/functions/kru-asset-library/api/:splat"